//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManagement.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int C_Id { get; set; }
        public string C_Name { get; set; }
    
        public virtual ICollection<Student> Student { get; set; }
    }
}
