//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManagement.DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public Student()
        {
            this.Class = new HashSet<Class>();
        }
        [DisplayName("Id")]
        public int S_Id { get; set; }
        [DisplayName("Name")]
        [Required]
        public string S_Name { get; set; }
        [DisplayName("Birthday")]
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime S_Birthday { get; set; }
        [DisplayName("Address")]
        public string S_Address { get; set; }
    
        public virtual ICollection<Class> Class { get; set; }
    }
}
